.retry: &retry
  retry:
    max: 2
    when:
      - unknown_failure
      - api_failure
      - runner_system_failure
      - missing_dependency_failure
      - runner_unsupported

variables:
  GIT_DEPTH: 10

stylesheet.html:
  variables:
    GIT_SUBMODULE_STRATEGY: none
  stage: test
  image: registry.gitlab.com/fuww/landing/hugo:v0.82.1-ext
  cache:
    key: "$CI_JOB_NAME"
    paths:
      - .npm
  before_script:
    - time npm ci --cache .npm --prefer-offline
  script:
    - time npm run build
  artifacts:
    paths:
      - layouts/partials/*stylesheet.html
    expire_in: 1 week
  <<: *retry

include:
   - local: exampleSite/.gitlab-ci.yml
